

CREATE TABLE contract
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    reference  VARCHAR(255),
    client_id  BIGINT,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    credit     INTEGER,
    version    INTEGER,
    CONSTRAINT pk_contract PRIMARY KEY (id)
);

ALTER TABLE contract
    ADD CONSTRAINT FK_CONTRACT_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

CREATE TABLE client
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255),
    deleted     BOOLEAN,
    national_id VARCHAR(255),
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

INSERT INTO client (name, national_id) VALUES ('Perico', '88888888R');
INSERT INTO contract (client_id) VALUES ('1');